Импортируйте библиотеку pandas как pd. Прочитайте датасет bookings.csv, находящийся по ссылке, с разделителем ;  и сохраните в переменную bookings. Затем запишите первые 7 строк в переменную bookings_head.

In [ ]:
import pandas as pd

In [9]:
bookings = pd.read_csv("bookings.csv", sep=";")

In [10]:
bookings

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [20]:
bookings_head = bookings.head(7)

Посмотрите на размеры таблицы. Сколько всего в ней столбцов?

In [22]:
bookings.shape

(119390, 21)

К какому типу относится большинство переменных?

In [24]:
bookings.dtypes

hotel                         object
is_canceled                    int64
lead_time                      int64
arrival_full_date             object
arrival_date_year              int64
arrival_date_month            object
arrival_date_week_number       int64
arrival_date_day_of_month      int64
stays_in_weekend_nights        int64
stays_in_week_nights           int64
stays_total_nights             int64
adults                         int64
children                     float64
babies                         int64
meal                          object
country                       object
reserved_room_type            object
assigned_room_type            object
customer_type                 object
reservation_status            object
reservation_status_date       object
dtype: object

💀 Сложное задание! 💀

Как вы уже могли заметить, при сборе датасета произошла небольшая ошибка, и названия колонок были записаны в неудобном для дальнейшей работы формате. Исправьте ситуацию: приведите названия столбцов к нижнему регистру и замените пробелы на знак нижнего подчёркивания. Например: Is Canceled -> is_canceled

Могут пригодиться: 

* rename
* str.lower
* str.replace
* columns

Сделал максимально прямолинейно, но работает

In [19]:
bookings =bookings.rename(columns={"Hotel": "hotel", "Is Canceled": "is_canceled", \
                         "Lead Time": "lead_time", "arrival full date": "arrival_full_date",\
                         "Is Canceled": "is_canceled", "Babies": "babies" \
                        , "Arrival Date Year": "arrival_date_year", "Arrival Date Month": "arrival_date_month"\
                        , "Arrival Date Week Number": "arrival_date_week_number", "Arrival Date Day of Month": "arrival_date_day_of_month"\
                        , "Stays in Weekend nights": "stays_in_weekend_nights", "Stays in week nights": "stays_in_week_nights"\
                        , "stays total nights": "stays_total_nights" , "Adults": "adults" \
                        , "Children": "children" , "Meal": "meal"\
                        , "Country": "country", "Reserved Room Type": "reserved_room_type"\
                        , "Assigned room type": "assigned_room_type", "customer type": "customer_type" \
                        , "Reservation Status": "reservation_status" , "Reservation status_date": "reservation_status_date"})

Попробую более разумный вариант

In [27]:
rename_col={}
for col in bookings.columns:
    rename_col[col]=col.replace(" ", "_").lower()

In [29]:
rename_col

{'hotel': 'hotel',
 'is_canceled': 'is_canceled',
 'lead_time': 'lead_time',
 'arrival_full_date': 'arrival_full_date',
 'arrival_date_year': 'arrival_date_year',
 'arrival_date_month': 'arrival_date_month',
 'arrival_date_week_number': 'arrival_date_week_number',
 'arrival_date_day_of_month': 'arrival_date_day_of_month',
 'stays_in_weekend_nights': 'stays_in_weekend_nights',
 'stays_in_week_nights': 'stays_in_week_nights',
 'stays_total_nights': 'stays_total_nights',
 'adults': 'adults',
 'children': 'children',
 'babies': 'babies',
 'meal': 'meal',
 'country': 'country',
 'reserved_room_type': 'reserved_room_type',
 'assigned_room_type': 'assigned_room_type',
 'customer_type': 'customer_type',
 'reservation_status': 'reservation_status',
 'reservation_status_date': 'reservation_status_date'}

In [30]:
bookings = bookings.rename(columns=rename_col)

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

💀 Сложное задание! 💀

Перейдём к исследованию данных! Пользователи из каких стран совершили наибольшее число успешных бронирований? 
Бронирование считается успешным, если в дальнейшем оно не было отменено (переменная is_canceled). В качестве ответа выберите страны, входящие в топ-5.

In [43]:
bookings.query("is_canceled == 0").country \
                .value_counts().head(5)

PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
Name: country, dtype: int64

На сколько ночей (stays_total_nights)  в среднем бронируют отели типа City Hotel? Resort Hotel? Запишите полученные значения в пропуски с точностью до 2 знаков после точки.

In [44]:
bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'stays_total_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved_room_type', 'assigned_room_type',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='object')

In [50]:
bookings.query("hotel == 'City Hotel'").stays_total_nights.mean().round(decimals=2)

2.98

In [51]:
bookings.query("hotel == 'Resort Hotel'").stays_total_nights.mean().round(decimals=2)

4.32